name: Lint

on: [pull_request]

jobs:
  lint-agentkit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdp-agentkit-core
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck

  lint-langchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdp-langchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck 