name: Unit Tests

on: [pull_request]

jobs:
  test-agentkit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdp-agentkit-core
    strategy:
      matrix:
        node-version: ['18', '20']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit

  test-langchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdp-langchain
    strategy:
      matrix:
        node-version: ['18', '20']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit 